<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<Platforms>x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
		<PackageReference Include="xunit" Version="2.5.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
		<PackageReference Include="NSubstitute" Version="5.3.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RolePlayer\RolePlayer.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Dalamud">
			<HintPath>$(AppData)\XIVLauncher\addon\Hooks\dev\Dalamud.dll</HintPath>
			<Private>true</Private>
		</Reference>
	</ItemGroup>
</Project>